# Site
name: "Millennial's Guide"
title: "Millennial's Guide"
description: "Life, the universe, and everything"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-143312047-1'
mailchimp-list: 'https://mlngd.us3.list-manage.com/subscribe/post?u=50d97e645033af5c70a35c88a&amp;id=58afba32d2'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  saleh:
    name: Saleh Hamadeh
    display_name: Saleh
    gravatar: b9c12f81c0431475b917f9c42ffd2036
    email: saleh@shamadeh.com
    web: https://shamadeh.com
    description: "Blog owner and primary author."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
